### ISSUE TITLE
Errors & warnings when running the site on windows

### ISSUE THREAD

**Issue by pzi** [dddwa/dddperth-website#161]
I pulled down recent `master` on my work windows PC and I get this error :( - however, it works just fine on my macbook.

![image](https://user-images.githubusercontent.com/2037851/56779357-38e66e80-680d-11e9-8722-3deff0d112e9.png)

When following the steps on https://fb.me/react-invalid-hook-call to figure out what's wrong the only thing I noticed was that `react-ga` is using a different version of React. However, upgrading that package didn't help. Neither did turning the arrow function into a named function. Didn't try much else as I was doing this at work and it works on OSX :|

The other thing is that on my windows machine I get a tonne of warnings about

```
[...] multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
```

But it's mostly related to some packages in `node_modules` /shrug.

**Comment by antonjb** [comment]
Anyone with a Windows machine able to see if this is still an issue? The Next updates might have resolved the issue but no idea.

**Comment by pzi** [comment]
Sorry, I no longer have access to a windows machine for testing 😅

**Comment by antonjb** [comment]
I'm going to close this and if someone with a Windows machine joins in development again we can see at that point.
