### ISSUE TITLE
2020 Agenda page returns HTTP404

### ISSUE THREAD

**Issue by mzaatar** [dddwa/dddperth-website#278]
Agenda page return Http 404

Cause: After we postponed 2020 to be 2021 so we fast forward the date and clicking on previous agenda link "https://dddperth.com/agenda/2020"

Solutions:
- Redirect 2020 page to 2019 or 
- Display a list in 2020 page referring to old agenda pages

**Comment by antonjb** [comment]
@ucichr what sort of content would you see living on the 2020 page? At the very least it could be the message about the cancellation but I'm sure we could do better.

**Comment by ucichr** [comment]
I'd go with any events we run at a minimum. Perhaps links to DDD Melbourne 
by Night too, next month?
