### ISSUE TITLE
Important dates should not move when transition to 'done' (opinionated)

### ISSUE THREAD

**Issue by Macca2805** [dddwa/dddperth-website#49]
![dddperth com_cfp](https://user-images.githubusercontent.com/5493721/39916678-cac3b882-553d-11e8-98e2-7ac88d4863bd.png)

In the current state this component resembles a todo list (which is probably how organisers see important dates). I don't believe this is correct as it means the list is no longer date ordered. I think attendees see this list as a timeline meaning the items should not be out of date order.

For example, https://github.com/Readify/DevEvents

**Comment by antonjb** [comment]
I'm going to close this as we never addressed it last year either. If there's still strong feels feel free to reopen the issue.
