### ISSUE TITLE
Accessibility: No visible focus indicators

### ISSUE THREAD

**Issue by robcrowley** [dddwa/dddperth-website#50]
Using the keyboard to navigate the site is difficult as there are no visible focus indicators to help users tell what they are about to click on or where they are in the page.

**Recommendation:** Design a focus style which suits the DDD brand and apply it to all interactive elements (links, buttons, forms). Alternatively remove all instances of `outline: 0`; and `outline: none` from the CSS and allow the default browser focus indicators to become visible.

**Comment by Macca2805** [comment]
Fixed in PR
