### ISSUE TITLE
Accessibility: Inform users that Explore mailto link on Sponsorship page will open in new application

### ISSUE THREAD

**Issue by robcrowley** [dddwa/dddperth-website#54]
The link "explore sponsorship opportunities" is a mail link so will trigger a new application to open, but users aren't made aware of this.

**Recommendation:** Ideally, a mail icon with appropriate alt content (e.g. "opens in your mail program of choice"). Alternatively visually hidden text will be needed in the link text.

**Comment by Macca2805** [comment]
Fixed in PR, issue can be closed
