### ISSUE TITLE
Accessibility: Add text to links in Footer

### ISSUE THREAD

**Issue by robcrowley** [dddwa/dddperth-website#66]
There is no link text nor indication of opening in a new window. The font icons are in the CSS, and there is no text available to screen readers (`title` attribute isn't reliable cross-browser / cross-screen reader).

**Recommendation:** Add some visually-hidden text inside each link. The link text should let non-sighted users know what will happen if they click the links, e.g. "DDDperth on Twitter, opens in a new window".

**Comment by pzi** [comment]
This seems to have been resolved by #86.

Alternative would be to move the text that was added as `title`s and `aria-label`s inside a `<span class="visually-hidden">`.
